
// TODO: add more gifs, more colors to each gif for future use
// future use aka select a random 7 from the 14 colors

// Gif Palette Info Object
const gifData = [
  {
    fileName: 'Arctic',
    colors: {
      'c1': '#8AA3B5',
      'c2': '#CDE1DA',
      'c3': '#D3D7C4',
      'c4': '#E9F8E3',
      'c5': '#ABC7D6',
      'c6': '#9F9E9B',
      'c7': '#58718A',
      'c8': '#404C58',
      'c9': '#382E29',
      'c10': '#826C5D',
      'c11': '#6A5D58',
      'c12': '#B4A591',
    },
  },
  {
    fileName: 'BrazilFire',
    colors: {
      'c1': '#A5602C',
      'c2': '#61402C',
      'c3': '#804C2E',
      'c4': '#836C61',
      'c5': '#522E1C',
      'c6': '#966E5B',
      'c7': '#D5BBE8',
      'c8': '#120905',
      'c9': '#BA9D85',
      'c10': '#B37538',
      'c11': '#B59970',
      'c12': '#C0A1AD',
    },
  },
  {
    fileName: 'Fiordland',
    colors: {
      'c1': '#A696A5',
      'c2': '#',
      'c3': '#',
      'c4': '#',
      'c5': '#',
      'c6': '#',
      'c7': '#',
      'c8': '#',
      'c9': '#',
      'c10': '#',
      'c11': '#',
      'c12': '#',
    },
  },
  {
    fileName: 'Kyrgyzstan',
    colors: {
      'c1': '#EA8A37',
      'c2': '#',
      'c3': '#',
      'c4': '#',
      'c5': '#',
      'c6': '#',
      'c7': '#',
      'c8': '#',
      'c9': '#',
      'c10': '#',
      'c11': '#',
      'c12': '#',
    },
  },
  {
    fileName: 'PortDePollenca',
    colors: {
      'c1': '#F7D15E',
      'c2': '#',
      'c3': '#',
      'c4': '#',
      'c5': '#',
      'c6': '#',
      'c7': '#',
      'c8': '#',
      'c9': '#',
      'c10': '#',
      'c11': '#',
      'c12': '#',
    },
  },
  {
    fileName: 'Rodorveld',
    colors: {
      'c1': '#C4B7A8',
      'c2': '#',
      'c3': '#',
      'c4': '#',
      'c5': '#',
      'c6': '#',
      'c7': '#',
      'c8': '#',
      'c9': '#',
      'c10': '#',
      'c11': '#',
      'c12': '#',
    },
  },
  {
    fileName: 'SnowBridge',
    colors: {
      'c1': '#E7F5FD',
      'c2': '#',
      'c3': '#',
      'c4': '#',
      'c5': '#',
      'c6': '#',
      'c7': '#',
      'c8': '#',
      'c9': '#',
      'c10': '#',
      'c11': '#',
      'c12': '#',
    },
  },
  {
    fileName: 'Thunderstorm',
    colors: {
      'c1': '#01040D',
      'c2': '#',
      'c3': '#',
      'c4': '#',
      'c5': '#',
      'c6': '#',
      'c7': '#',
      'c8': '#',
      'c9': '#',
      'c10': '#',
      'c11': '#',
      'c12': '#',
    },
  },
];


export default gifData;
